common/modules/articles/models/Attachments.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package yii2-articles
* @version 0.6.3
*/

namespace common\modules\articles\models;

use Yii;

class Attachments extends Articles
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%article_attachments}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['itemid', 'title', 'titleAttribute'], 'required'],
            [['itemid', 'hits'], 'integer'],
            [['titleAttribute'], 'string'],
            [['filename', 'title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('articles', 'ID'),
            'itemid' => Yii::t('articles', 'Article'),
            'filename' => Yii::t('articles', 'Filename'),
            'title' => Yii::t('articles', 'Title'),
            'titleAttribute' => Yii::t('articles', 'Title Attribute'),
            'hits' => Yii::t('articles', 'Hits'),
        ];
    }

    /**
     * check if current user is the author from the article id
     * @return bool
     */
    public function isUserAuthor()
    {
        if ( Yii::$app->user->identity->id == $this->getUserAuthor() )
        {
            return true;
        } else {
            return false;
        }
    }

    /**
     * return user of the author from the article
     * @return bool
     */
    public function getUserAuthor()
    {
        return $this->getItem()->one()->created_by;
    }

    /**
     * Delete File attached
     * @return mixed the uploaded image instance
     */
    public function deleteFile()
    {
        $file = Yii::getAlias(Yii::$app->controller->module->attachPath).$this->filename;

        // check if image exists on server
        if ( empty($this->filename) || !file_exists($file) ) {
            return false;
        }

        // check if uploaded file can be deleted on server
        if (unlink($file)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(Items::className(), ['id' => 'itemid']);
    }
}

common/modules/articles/controllers/ItemsController.php
<?php

/**
 * @copyright Copyright &copy; Gogodigital Srls
 * @company Gogodigital Srls - Wide ICT Solutions
 * @website http://www.gogodigital.it
 * @github https://github.com/cinghie/yii2-articles
 * @license GNU GENERAL PUBLIC LICENSE VERSION 3
 * @package yii2-articles
 * @version 0.6.3
 */
namespace common\modules\articles\controllers;

use Yii;
use common\modules\articles\models\Items;
use common\modules\articles\models\ItemsSearch;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use common\models\Categories;
use yii\helpers\Json;
use common\modules\articles\models\Articles;
use yii\web\UploadedFile;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\modules\articles\models\ArticleTags;

/**
 * ItemsController implements the CRUD actions for Items model.
 */
class ItemsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'deleteimage',
                            'deletemultiple',
                            'changestate',
                            'activemultiple',
                            'deactivemultiple',
                            'category-products',
                            'type-category',
                            'upload-file'
                        ],
                        'roles' => [
                            '@'
                        ]
                    ],
                    [
                        'allow' => true,
                        'actions' => [
                            'view',
                            'category'
                        ],
                        'roles' => [
                            '?',
                            '@'
                        ]
                    ]
                ],
                'denyCallback' => function () {
                    throw new \Exception ('You are not allowed to access this page');
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'changestate' => [
                        'post'
                    ],
                    'delete' => [
                        'post'
                    ],
                    'deleteImage' => [
                        'post'
                    ],
                    'deletemultiple' => [
                        'post'
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all Items models.
     *
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        // Check RBAC Permission
        if ($this->userCanIndex()) {
            $searchModel = new ItemsSearch ();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider
            ]);
        } else {
            throw new ForbiddenHttpException ();
        }
    }

    /**
     * Displays a single Items model.
     *
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionView($alias = null)
    {
        $this->layout = "cms";
        $model = Items::find()->where(["alias" => $alias])->one();
        if ($model !== null) {
            $model->hits = $model->hits + 1;
            $model->save();
            $category = new \common\modules\articles\models\Categories ();
            $topCateogryItem = $category->getTopViewdItemsByCategory($model->catid, 'hits');
            $articleTags = $model->getArticleTags();
            $articleGallery = [$model->getImageUrl()];
            $articleImages = $model->imageGallery;
            foreach ($articleImages as $image) {
                $articleGallery[] = $image->getImageUrl();
            }
            return $this->render('view', [
                'model' => $model,
                'topCateogryItem' => $topCateogryItem,
                'articleTags' => $articleTags,
                'articleGallery' => $articleGallery
            ]);
        } else {
            throw new NotFoundHttpException ('The requested page does not exist.');
        }
    }

    /**
     * Creates a new Items model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionCreate()
    {
        // Check RBAC Permission
        if ($this->userCanCreate()) {
            $model = new Items ();

            if ($model->load(Yii::$app->request->post())) {
                // Set Modified as actual date
                $model->modified = "0000-00-00 00:00:00";

                // If alias is not set, generate it
                if ($_POST ['Items'] ['alias'] == "") {
                    $model->alias = $model->generateAlias($model->title);
                }
                if (!empty ($_POST ['Items'] ['tags'])) {
                    $tags = [];
                    foreach ($model->tags as $tagId) {
                        if ($tagId > 0) {
                            $tags [] = $tagId;
                        } else {
                            $articleTags = new ArticleTags ();
                            $articleTags->name = $tagId;
                            $articleTags->save();
                            $tags [] = $articleTags->id;
                        }
                    }
                    $model->tags = implode(",", $tags);
                }

                // Upload Image and Thumb if is not Null
                $imagePath = Yii::getAlias(Yii::$app->controller->module->itemImagePath);
                $thumbPath = Yii::getAlias(Yii::$app->controller->module->itemThumbPath);
                $imgNameType = Yii::$app->controller->module->imageNameType;
                $imgOptions = Yii::$app->controller->module->thumbOptions;
                $imgName = $model->title;
                $fileField = "image";

                // Create UploadFile Instance
                $image = $model->uploadFile($imgName, $imgNameType, $imagePath, $fileField);

                if ($model->save()) {

                    // upload only if valid uploaded file instance found
                    if ($image !== false) {
                        // save thumbs to thumbPaths
                        $model->createCustomThumbImages($image, $imagePath, $imgOptions, $thumbPath);
                    }

                    // Set Success Message
                    Yii::$app->session->setFlash('success', Yii::t('articles', 'Item has been created!'));

                    return $this->redirect([
                        'index'
                    ]);
                } else {

                    // Set Error Message
                    Yii::$app->session->setFlash('error', Yii::t('articles', 'Item could not be saved!'));

                    return $this->render('create', [
                        'model' => $model
                    ]);
                }
            } else {

                return $this->render('create', [
                    'model' => $model
                ]);
            }
        } else {
            throw new ForbiddenHttpException ();
        }
    }

    /**
     * Updates an existing Items model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        // Check RBAC Permission
        if ($this->userCanUpdate($id)) {
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post())) {

                // Set Modified as actual date
                $model->modified = date("Y-m-d H:i:s");

                // Set Modified by User
                $model->modified_by = Yii::$app->user->identity->id;

                // If alias is not set, generate it
                if ($_POST ['Items'] ['alias'] == "") {
                    $model->alias = $model->generateAlias($model->title);
                }
                if (!empty ($_POST ['Items'] ['tags'])) {
                    $tags = [];
                    foreach ($model->tags as $tagId) {
                        if ($tagId > 0) {
                            $tags [] = $tagId;
                        } else {
                            $articleTags = new ArticleTags ();
                            $articleTags->name = $tagId;
                            $articleTags->save();
                            $tags [] = $articleTags->id;
                        }
                    }
                    $model->tags = implode(",", $tags);
                }

                // Upload Image and Thumb if is not Null
                $imagePath = Yii::getAlias(Yii::$app->controller->module->itemImagePath);
                $thumbPath = Yii::getAlias(Yii::$app->controller->module->itemThumbPath);
                $imgNameType = Yii::$app->controller->module->imageNameType;
                $imgOptions = Yii::$app->controller->module->thumbOptions;
                $imgName = $model->title;
                $fileField = "image";

                // Create UploadFile Instance
                $image = $model->uploadFile($imgName, $imgNameType, $imagePath, $fileField);

                if ($model->image == false && $image === false) {

common/modules/articles/views/attachments/_form.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package yii2-articles
* @version 0.6.3
*/

use cinghie\articles\assets\ArticlesAsset;
use kartik\widgets\ActiveForm;
use kartik\widgets\FileInput;
use kartik\widgets\Select2;
use yii\helpers\Html;

// Load Articles Assets
ArticlesAsset::register($this);
$asset = $this->assetBundles['cinghie\articles\assets\ArticlesAsset'];

// Load info
$attachType       = Yii::$app->controller->module->attachType;
$select2articles = $model->getItemsSelect2();

if ($model->isNewRecord) {
    $hits = "0";
} else {
    $hits = $model->hits;
}

?>

<div class="attachments-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype'=>'multipart/form-data'
        ],
    ]); ?>

    <div class="row">

        <div class="col-lg-12">

            <div class="col-lg-12">

                <p class="bg-info">
                    <?= Yii::t('articles', 'Allowed Extensions')?>: <?= $attachType ?>
                </p>

            </div>

            <div class="col-lg-5">

                <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'filename')->widget(FileInput::classname(), [
                    'options' => [
                        'accept' => $attachType
                    ],
                    'pluginOptions' => [
                        'previewFileType' => 'image',
                        'showUpload'      => false,
                        'browseLabel'     => Yii::t('articles', 'Browse &hellip;'),
                    ],
                ]); ?>

                <?= $form->field($model, 'itemid')->widget(Select2::classname(), [
                    'data' => $select2articles,
                    'addon' => [
                        'prepend' => [
                            'content'=>'<i class="fa fa-file-text-o"></i>'
                        ]
                    ],
                ]); ?>

            </div>

            <div class="col-lg-7">

                <?= $form->field($model, 'titleAttribute')->textarea(['rows' => 4]) ?>

                <?= $form->field($model, 'hits')->widget(Select2::classname(), [
                    'data' => [
                        $hits => $hits
                    ],
                    'options' => [ 'disabled' => 'disabled' ],
                    'addon' => [
                        'prepend' => [
                            'content'=>'<i class="glyphicon glyphicon-eye-open"></i>'
                        ]
                    ],
                ]); ?>

            </div>

            <div class="col-lg-12">

                <div class="form-group">
                    <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </div>

            </div>

        </div>

    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/articles/views/attachments/_search.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package yii2-articles
* @version 0.6.3
*/

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="attachments-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'itemid') ?>

    <?= $form->field($model, 'filename') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'titleAttribute') ?>

    <?php // echo $form->field($model, 'hits') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/articles/views/attachments/create.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package articles
* @version 0.6.3
*/

use yii\helpers\Html;

// Set Title and Breadcrumbs
$this->title = Yii::t('articles', 'Create Attachment');
$this->params['breadcrumbs'][] = ['label' => Yii::t('articles', 'Attachments'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

// Render Yii2-Articles Menu
echo Yii::$app->view->renderFile('@common/modules/articles/views/default/_menu.php');

?>
<div class="attachments-create">

    <?php if(Yii::$app->getModule('articles')->showTitles): ?>
        <div class="page-header">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    <?php endif ?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

common/modules/articles/views/attachments/index.php
<?php

/**
 * @copyright Copyright &copy; Gogodigital Srls
 * @company Gogodigital Srls - Wide ICT Solutions
 * @website http://www.gogodigital.it
 * @github https://github.com/cinghie/yii2-articles
 * @license GNU GENERAL PUBLIC LICENSE VERSION 3
 * @package articles
 * @version 0.6.3
 */

use common\modules\articles\assets\ArticlesAsset;
use kartik\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

// Load Articles Assets
ArticlesAsset::register($this);
$asset = $this->assetBundles['cinghie\articles\assets\ArticlesAsset'];

// Set Title and Breadcrumbs
$this->title = Yii::t('articles', 'Attachments');
$this->params['breadcrumbs'][] = $this->title;

// Render Yii2-Articles Menu
echo Yii::$app->view->renderFile('@vendor/cinghie/articles/views/default/_menu.php');

// Register action buttons js
$this->registerJs('
    $(document).ready(function()
    {
        $("a.btn-update").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("'.Yii::t("articles", "Select at least one item").'");
            } else if(selectedId.length>1){
                alert("'.Yii::t("articles", "Select only 1 item").'");
            } else {
                var url = "'.Url::to(['/articles/attachments/update']).'?id="+selectedId[0];
                window.location.href= url;
            }
        });
        $("a.btn-delete").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("'.Yii::t("articles", "Select at least one item").'");
            } else {
                var choose = confirm("'.Yii::t("articles", "Do you want delete selected items?").'");

                if (choose == true) {
                    $.ajax({
                        type: \'POST\',
                        url : "'.Url::to(['/articles/attachments/deletemultiple']).'?id="+selectedId,
                        data : {ids: selectedId},
                        success : function() {
                            $.pjax.reload({container:"#w2"});
                        }
                    });
                }
            }
        });
        $("a.btn-preview").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("'.Yii::t("articles", "Select at least one item").'");
            } else if(selectedId.length>1){
                alert("'.Yii::t("articles", "Select only 1 item").'");
            } else {
                var url = "'.Url::to(['/articles/attachments/view']).'?id="+selectedId[0];
                window.location.href= url;
            }
        });
    });
');

?>
<div class="attachments-index">

    <?php if(Yii::$app->getModule('articles')->showTitles): ?>
        <div class="page-header">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    <?php endif ?>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php Pjax::begin() ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'pjaxSettings'=>[
            'neverTimeout' => true,
        ],
        'columns' => [
            [
                'class' => '\kartik\grid\CheckboxColumn'
            ],
            [
                'attribute' => 'title',
                'format' => 'html',
                'hAlign' => 'center',
                'value' => function ($model) {
                    $url = urldecode(Url::toRoute(['attachments/update', 'id' => $model->id]));
                    return Html::a($model->title,$url);
                }
            ],
            [
                'attribute' => 'itemid',
                'format' => 'html',
                'hAlign' => 'center',
                'value' => 'item.title',
                'value' => function ($data) {
                    $url  = urldecode(Url::toRoute(['items/update', 'id' => $data->itemid]));
                    $item = isset($data->item->title) ? $data->item->title : "";

                    if($item!="") {
                        return Html::a($item,$url);
                    } else {
                        return Yii::t('articles', 'Nobody');
                    }
                }
            ],
            [
                'attribute' => 'filename',
                'hAlign' => 'center',
            ],
            [
                'attribute' => 'hits',
                'hAlign' => 'center',
                'width' => '8%',
            ],
            [
                'attribute' => 'id',
                'hAlign' => 'center',
                'width' => '8%',
            ],
        ],
        'responsive' => true,
        'hover' => true,
        'panel' => [
            'heading'    => '<h3 class="panel-title"><i class="fa fa-paperclip"></i></h3>',
            'type'       => 'success',
            'before'     => '<span style="margin-right: 5px;">'.
                Html::a('<i class="glyphicon glyphicon-plus"></i> '.Yii::t('articles', 'New'),
                    ['create'], ['class' => 'btn btn-success']
                ).'</span><span style="margin-right: 5px;">'.
                Html::a('<i class="glyphicon glyphicon-pencil"></i> '.Yii::t('articles', 'Update'),
                    '#', ['class' => 'btn btn-update btn-warning']
                ).'</span><span style="margin-right: 5px;">'.
                Html::a('<i class="glyphicon glyphicon-minus-sign"></i> '.Yii::t('articles', 'Delete'),
                    '#', ['class' => 'btn btn-delete btn-danger']
                ).'</span><span style="margin-right: 5px;">'.
                Html::a('<i class="fa fa-eye"></i> '.Yii::t('articles', 'Preview'),
                    '#', ['class' => 'btn btn-preview btn-info']
                ).'</span>',
            'after' => Html::a(
                '<i class="glyphicon glyphicon-repeat"></i> '.Yii::t('articles', 'Reset Grid'), ['index'], ['class' => 'btn btn-info']
            ),
            'showFooter' => false
        ],
    ]); ?>

    <?php Pjax::end() ?>

</div>

common/modules/articles/views/attachments/update.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package articles
* @version 0.6.3
*/

use yii\helpers\Html;

// Set Title and Breadcrumbs
$this->title = Yii::t('articles', 'Update {modelClass}: ', ['modelClass' => 'Attachments',]) . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('articles', 'Attachments'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

// Render Yii2-Articles Menu
echo Yii::$app->view->renderFile('@common/modules/articles/views/default/_menu.php');

?>
<div class="attachments-update">

    <?php if(Yii::$app->getModule('articles')->showTitles): ?>
        <div class="page-header">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    <?php endif ?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

common/modules/articles/views/attachments/view.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package yii2-articles
* @version 0.6.3
*/

use yii\helpers\Html;
use yii\widgets\DetailView;

// Set Title and Breadcrumbs
$this->title = $model->title;
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="attachments-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'itemid',
            'filename',
            'title',
            'titleAttribute:ntext',
            'hits',
        ],
    ]) ?>

</div>